### ISSUE TITLE
under linux every button works as button number 1 

### ISSUE THREAD

**Issue by reinholdPL** [FreeJoy-Team/FreeJoy#102]
Firstly, I would like to thank you for all your work with Freejoy. A wonderful job.
I have problem on linux. When I run jstest-gtk (or jstest) I can see correct number of buttons and axes, but every button work as button number 1. It doesn't matter which button I press, always the button number 1 shows as pressed. FreeJoyConfiguratorQt correctly detects each button press.

Problem persists on both Ubuntu 20.04 and Debian 10.8. I am using the latest version of Freejoy v1.7.0.
I'm sure that everything is fine with electronics and configuration because device works 
properly on Windows 10 and Windows XP (each button works as it should).

Maybe it's a problem with usb hid implementation on linux? I will be grateful for any help.

**Comment by Reksotiv** [comment]
Thanks for report. I confirm there is a bug. Latest working version on debian v1.6.2b1. Working on fix

**Comment by reinholdPL** [comment]
Thank you for quick reply. Do you think this commit might solve the issue?

#103

**Comment by Reksotiv** [comment]
yes

**Comment by reinholdPL** [comment]
just wanted to confirm that this commit gets the job done and everything works correctly under linux now.

**Comment by Reksotiv** [comment]
should works. This is an old known issue and we forgot to change it in 1.7. Changing 0x00 to 0x02 fixes the problem
![image](https://user-images.githubusercontent.com/29454172/111442327-4cf52b00-8719-11eb-8de5-d009e87df155.png)

**Comment by Reksotiv** [comment]
fixed in [v1_7_0b2](https://github.com/FreeJoy-Team/FreeJoy/releases)
