### ISSUE TITLE
not problem but question

### ISSUE THREAD

**Issue by pipes80-collab** [FreeJoy-Team/FreeJoy#106]
is this https://github.com/ufocia/FreeJoy/releases problem solving for assetto corsa on linux?
i have try to flash but not detect freejoy

**Comment by ufocia** [comment]
It fixes the issue of all buttons' presses being conflated into button one presses. This is just the application without the boot loader. So the application needs to be flashed from the new QT configurator. I don't believe it will work with the old configurator. If freejoy was never detected this will not help. If it was not detected the value of the resistors on the USB pins should be checked as some of the devices have the wrong resistor which cause them to not be detected. If the resistor is not a problem then the official hex file should be flashed with a hardware programmer and then the fixed version should be flashed using the configurator.

**Comment by pipes80-collab** [comment]
that solved with flash from app qt thanks for help
