### ISSUE TITLE
All axes are displayed even if no axe is defined

### ISSUE THREAD

**Issue by godor2008** [FreeJoy-Team/FreeJoy#11]
![image](https://user-images.githubusercontent.com/1040630/73799029-60676000-47bd-11ea-993e-fc6100ab8c13.png)
I selected only buttons in latest configurator. But Windows game controller setup shows that there are lot of axes

**Comment by vostrenkov** [comment]
Yes, it is ok.
USB HID descriptor is the same for all configurations. You will see 8 axes and 128 buttons even if nothing selected. Not selected axes always have 0 value and not selected buttons always have false state so they won't bother you too much

**Comment by godor2008** [comment]
And will it be implementable in future to remove not used axis/buttons?

**Comment by vostrenkov** [comment]
It is possible, but i don't see a lot of reasons to do this now. I will add this task to my list with low priority

**Comment by vostrenkov** [comment]
Dynamic HID config option is now available in version v1.3.4. Check out releases page
