### ISSUE TITLE
Linux Problem

### ISSUE THREAD

**Issue by gokhanhas** [FreeJoy-Team/FreeJoy#111]
First of all, I would like to thank those who contributed to developing such software and publishing it as open source.

My problem is as follows. When I connect the device in the QTCOnfigurator app, its name comes on, but disconnect and constantly in the console - Open HID device №1. VID "0483", PID "5757", Serial number "" - returns error. While there is no problem in WIndows, there is this problem in linux.

In addition, I can see the device in "jtest-gtk" application. The settings are working properly. However, ETS2 does not appear as a controller, for example. ETS2 also appears when I plug in my own gamepad. Again I can play on Windows without any problem.
I am using Ubuntu 20.04 LTS. UPD. v1_7_0b2.hex and UPD. I tried the v1_7_0b3.hex files separately. Is there anything else done for Linux other than uploading .hex files? What's the point I'm missing? Thanks.

Note : I just connected 3 potentiometers to the STM32 board.

![1](https://user-images.githubusercontent.com/48176668/114739470-93a66700-9d51-11eb-9f50-371a5c6bd30e.png)
![2](https://user-images.githubusercontent.com/48176668/114739694-c5b7c900-9d51-11eb-9f87-d4865a6271e0.png)

**Comment by Reksotiv** [comment]
Hi. https://github.com/FreeJoy-Team/FreeJoyConfiguratorQt 
![image](https://user-images.githubusercontent.com/29454172/114742322-4b3c7880-9d54-11eb-8b17-511a9643397c.png)

**Comment by gokhanhas** [comment]
Thanks for the very quick reply.  Unfortunately I haven't read it fully.  After doing, the QT app is now connected without any problems.  However, for example, ETS2 did not recognize the game as a gamepad.  Is there anything you can fix about this problem?  Thank you very, very much.

**Comment by Reksotiv** [comment]
I cannot run games in a virtual machine. Don't know why it doesn't work. Maybe later i'll try to install it on main PC.
Have you tried other games?

**Comment by gokhanhas** [comment]
I will try to download other games right now.  Thanks again for your help.  I am using the system as dual boot.

UPDATE : Unfortunately I also tried it in Rocket League and it didn't work. When my own gamepad is running, Freejoy does not work in games although it works in jtest-gtk.

**Comment by Reksotiv** [comment]
I checked. ETS does not see the controller if output is turned off for X and Y axes

**Comment by gokhanhas** [comment]
Hello, I just saw the message. Sorry. Does linux see in other ways? I use the X, Y and Z axes. I use three potentiometers.

**Comment by Reksotiv** [comment]
Hi. You are right, only the axes are not enough for linux. You need to add at least 1 button
![image](https://user-images.githubusercontent.com/29454172/115157768-b0190b00-a093-11eb-93bb-613d58bf9076.png)

**Comment by gokhanhas** [comment]
Thank you so much.  I will find a button and try it as soon as possible.

**Comment by Reksotiv** [comment]
you don't need a real button, just add Button GND/VCC in the configurator on any pin and set logical button

**Comment by gokhanhas** [comment]
Thanks, very good then.  I will try immediately.

**Comment by gokhanhas** [comment]
I add button by using configurator and then it will works. I played ETS2 in linux. Game saw the STM32 by gamepad. Thanks for your helping.

**Comment by Reksotiv** [comment]
you are welcome
