### ISSUE TITLE
Windows 10 Issue

### ISSUE THREAD

**Issue by snagov** [FreeJoy-Team/FreeJoy#116]
Hi, i am flashing like you indicate at instructions, but Windows 10 and 7 not recognize the USB Device. I flashing the board with 1.7.0 B1, B2 & B3 with same results.

Any Idea?

https://prnt.sc/12l6jmb

**Comment by vostrenkov** [comment]
discussing here: https://github.com/FreeJoy-Team/FreeJoyWiki/issues/17
