### ISSUE TITLE
Encoder output valut not directly bound to raw limit

### ISSUE THREAD

**Issue by FlisherOfatale** [FreeJoy-Team/FreeJoy#119]
In version 1.7.0b3, when I use the following setting, if I got under or above the max raw value, the out value stay at the limit, but won't come back in the normal range until the raw input is back in the minim/maximum value.

If we make 1 turn over the limit, we need to get back 1 turn before it move again in the other direction.
I'm not sure if it's the intended behavior for axis.

I tested with Fast Encoder and also EncoderA/B on channel 1 using B12/B13.
I'm available on the Hotas/DIY Discord if you need any clarifications.

Note that I used a smaller limit (-100/100) for the screnshoot, but it also happen with the default 32k

![image](https://user-images.githubusercontent.com/37115003/118383069-c64db480-b5c8-11eb-9f77-b65d71600fea.png)

**Comment by vostrenkov** [comment]
fixed in https://github.com/FreeJoy-Team/FreeJoy/commit/2cb45075c7fcda9a3e6c3aa98b69fba3f7339833
