### ISSUE TITLE
Encoders in button matrix

### ISSUE THREAD

**Issue by altoing** [FreeJoy-Team/FreeJoy#12]
Can you please implement support for rotary encoders connected in button matrix? It will be very useful.

**Comment by vostrenkov** [comment]
Can you give me an example of such connection?

**Comment by altoing** [comment]
Like in mmjoy2:
https://github.com/MMjoy/mmjoy_en/blob/master/img/Hardware%20connection/common_hardware_connections.png

**Comment by vostrenkov** [comment]
Ok, i will take it into account

**Comment by vostrenkov** [comment]
Encoder connection in button matrix is added in v1.3.4

**Comment by altoing** [comment]
Thank you!
