### ISSUE TITLE
About sensors voltage 

### ISSUE THREAD

**Issue by cagri-yuksel** [FreeJoy-Team/FreeJoy#131]
Hi i have question about 5V sensors. I read wiki and see sensors voltage always 3.3v. I don't have supporting 3v sensor. If i use ugn3503 hall effect sensor with 5v its okey? Also i have 74hc166 shift register using with 5v on arduino. Can i use sensors with 5v?
Before finish question why do you recommend capacitor with hall effect and which capacity capacitor is okey?
Sorry for awful english.

Thank you for your hard working.

**Comment by vostrenkov** [comment]
Hey!
STM32 does not support 5V logic levels (though some pins are 5V tolerant). That means it is better to use 3.3V sensors and other periphery. 
74HC165 can easily work with 3.3V supply so not problem here to use it
UGN3503 will not work properly with 3.3V supply voltage. So you have to supply it from 5V and use voltage divider circuit to scale your 5V output to 3.3V maximum
