### ISSUE TITLE
Same pins not working right CH32 clone blue pill

### ISSUE THREAD

**Issue by cagri-yuksel** [FreeJoy-Team/FreeJoy#132]
Hello i got CH32 label clone blue pill. Everyting working well currently using FreeJoy_1_7_0b3 version. 

Here problem B4 B1 and B0 pins when i try to use as button just blinking randomly. 

Maybe this is problem with card maybe software not compatible with clone bluepill, i check all short circuit everyting looks fine.
Do you think look clone cards and support them? Finding real st chip in market is really hard.

Thank you for hard working.
![ch32](https://user-images.githubusercontent.com/50049470/130151251-b2a1a9d3-1c6a-4514-9cc1-fa0f0e580d03.gif)

**Comment by vostrenkov** [comment]
Hey
Unfortunately there it a big variety of STM chip clones. Some of them works just fine but the others have random issues. It is quite hard to add support for that

**Comment by cagri-yuksel** [comment]
Thank you for answer sir,  you are already told it's a hobby project. Thank you for your hard working here.

**Comment by vostrenkov** [comment]
After fixing major bugs of v1.7.0 I gonna port this project to STM32F401 chip. There are not that many clones for it and chips are easier to get

**Comment by cagri-yuksel** [comment]
It's a amazing news. Also cheaper than bluepill.

Oh i forgot to tell about CH32F103 how to flash. If you can't flash with Stm cube you have to use CH tool. You can found it from offically wch website or
Directly dowloand link is: **http://www.wch.cn/downloads/file/299.html?time=2020-11-30%2015:18:58&code=ouWsNYROFLrhEkY7iw9Sm8Ge9d0fbmnEpvPKJDbb**  
**only work with UART**
