### ISSUE TITLE
Pressed buttons bouncing.

### ISSUE THREAD

**Issue by altoing** [FreeJoy-Team/FreeJoy#14]
All buttons in button matrix that a pressed down, start bouncing off after few seconds, it even reproducing with one solid wire between pins.
Here video example - https://screencast-o-matic.com/watch/cYnYbNwE3z

**Comment by vostrenkov** [comment]
Thanks for response, I will check it today

**Comment by vostrenkov** [comment]
Fixed. Check releases for 1.3.3b4 version

**Comment by altoing** [comment]
button 1-32 did not bounce now, but 33 and beyond bouncing.

**Comment by vostrenkov** [comment]
Please check v1.3.3b5

**Comment by altoing** [comment]
No bouncing any more, thank you!
