### ISSUE TITLE
Unrecognized Device when there are no pin configured as Analog input.

### ISSUE THREAD

**Issue by jieweiyang** [FreeJoy-Team/FreeJoy#20]
At least one pin configure as Axis_Analog, otherwise the device will be become Unrecognized USB 
 Device after config written.

Axes config already disabled all.
Dynamic HID enable/disable same.

**Comment by vostrenkov** [comment]
Please save config to file and upload somewhere i will be able to download it

**Comment by jieweiyang** [comment]
The issue could be with the configurator. It crashed when try to save with no pin configured with Axis.

Firmware: 1.4.1b2
Configurator: 1.4.1b3

**Comment by vostrenkov** [comment]
Thanks, i will check soon

**Comment by vostrenkov** [comment]
I fixed this bug. Check for v1.4.1b3
