### ISSUE TITLE
Hi, just can't find any installer

### ISSUE THREAD

**Issue by freakerman21** [FreeJoy-Team/FreeJoy#25]
I cannot find any way of installation.

**Comment by vostrenkov** [comment]
![image](https://user-images.githubusercontent.com/21309063/78423812-b8adc780-7671-11ea-9b0b-56ca71f564b1.png)

https://github.com/FreeJoy-Team/FreeJoy/releases
https://github.com/FreeJoy-Team/FreeJoyConfigurator/releases
https://github.com/FreeJoy-Team/FreeJoyConfigurator/wiki
https://github.com/FreeJoy-Team/FreeJoy/wiki

**Comment by freakerman21** [comment]
So I download it and have two files. One .bin and one .hex. What should I do next??
Sorry I don't know how to do this.

**Comment by vostrenkov** [comment]
You need to program your BluePill board with .hex file. There are instructions at wiki page: https://github.com/FreeJoy-Team/FreeJoy/wiki/Quickstart-guide

After programming you should install configurator utility and make needed setup for your application. Instructions are also available at wiki:
https://github.com/FreeJoy-Team/FreeJoyConfigurator/wiki

**Comment by freakerman21** [comment]
Yes, I have programmed my blue pill but I don't see any installer or .exe or anything like that in any folder zip. 
I have also the OSH Studio and it works but I don't know how to make potenetiometers to work.
I am trying to make an analog clutch but I can't.

**Comment by freakerman21** [comment]
![image](https://user-images.githubusercontent.com/44001099/78424251-7930ac80-766c-11ea-965a-ddfc9a07e874.png)

**Comment by vostrenkov** [comment]
Use links from my first reply to get zip with installer of FreeJoy Configurator.
