### ISSUE TITLE
Teamspeak does not recognize Buttons

### ISSUE THREAD

**Issue by Jens72** [FreeJoy-Team/FreeJoy#27]
hello,
i am using Freejoy for a buttonplate . i try to assign a button  to push to talk .

windows gamecontroller sees every button.   all games i have tested too,
when i try to assign a button in teamspeak for  push to talk something strange happens:
teamspeak accepts only to buttons of 14 working and both buttons are recognized as button 2 of gamecontroller.
i tried to change the logic button -> physical button.  windows recognized the change.   teamspeak only recognizes the two buttons before as button 2.

i use version 1.4.1.b5

**Comment by vostrenkov** [comment]
Please share your configuration file ("save config to file" button)

**Comment by Jens72** [comment]
[osw_f1_gnd_neusort.zip](https://github.com/FreeJoy-Team/FreeJoy/files/4493042/osw_f1_gnd_neusort.zip)

**Comment by vostrenkov** [comment]
I'm able to reproduce this issue too and I have no idea why. Looks like the problem is in game controller extension for teamspeak. It may fail when several game devices are connected at the same time

**Comment by Jens72** [comment]
usually i use several usb controllers at once .  old buttonbox with mmjoy, another  one wih osh buttton controller, simhub dash , ffb wheel and now freejoy for the wheel button plate.
buttons of mmjoy and osh controller can be assigned.

even when only wheel and freejoy is connected the problem of posting #1  is still there.

i

**Comment by vostrenkov** [comment]
I tried with different PCs and system configs but still have no idea how to fix it. I've found threads with similar problem: 
https://theairtacticalassaultgroup.com/forum/showthread.php?t=27796
https://forum.teamspeak.com/threads/131306-Gamepad-and-joystick-hotkey-support-plugin-not-loading
https://forum.teamspeak.com/threads/9326-Binding-Joystick-buttons-to-speak

As a workaround you can use [svmapper](https://theairtacticalassaultgroup.com/forum/attachment.php?attachmentid=9632&d=1400316623) to emulate keyboard press and bind it to TS

**Comment by Jens72** [comment]
thank you. i did not know this program. it seem to work now.  :)
