### ISSUE TITLE
USB HIDName is incorrect

### ISSUE THREAD

**Issue by betgear** [FreeJoy-Team/FreeJoy#3]
Hi,

Retrieved HID name is not correct in the PC app.

![image](https://user-images.githubusercontent.com/7520096/71896370-844a6e00-314b-11ea-990e-ea44c0c67285.png)

The name appears in the APP as 'r during stacking' which is obviously a partial string from somewhere random in memory

![image](https://user-images.githubusercontent.com/7520096/71896441-b8be2a00-314b-11ea-958f-4859e8c4a131.png)

Additionally I cannot see to save a config file to the STM32, I tried creating a debug build to get more information for you, but unfortunately the debug build will not fit in the microcontrollers memory.

**Comment by vostrenkov** [comment]
Hello,
looks like the application don't write default config at first startup. The reason can be flash memory at that area is not empty during first run. Please try to do full chip erase and try to load code again.

**Comment by betgear** [comment]
Hi,

Yes, that makes sense. It works now :)

Why not use a checksum on the config data, if the checksum does not match, write the default configuration data with correct checksum.

**Comment by vostrenkov** [comment]
I didn't think this could happen :)
I will add some kind of protection to future commits.
