### ISSUE TITLE
4-directional Stick Switch + Encoder + Center-push button

### ISSUE THREAD

**Issue by 0xcore** [FreeJoy-Team/FreeJoy#34]
Hi,

Does anyone know if it is possible to use with Freejoy ?

![imagen](https://user-images.githubusercontent.com/38330148/85997581-f53b5600-ba09-11ea-9807-7c2ad56ff7a4.png)
![imagen](https://user-images.githubusercontent.com/38330148/85997641-0c7a4380-ba0a-11ea-9ef0-b8e9d85cdeda.png)

https://tech.alpsalpine.com/prod/e/html/multicontrol/switch/rkjxt/rkjxt1f42001.html

I have seen that it is possible with Arduino & Teensy but I suppose it would need some modification to work with FreeJoy.

Arduino
https://github.com/darjusp/test

Teensy
https://www.xsimulator.net/community/threads/teensy-lc-arduino-scripts.9681

Thanks!

**Comment by vostrenkov** [comment]
Hi,
I don't see a reason it should not work here. You dont even need external pulling resistors, bluepill provides internal pull-ups and pull-downs. Just connect terminals as ordinary buttons (Button VCC or Button GND) and set encoder inputs as Encoder A and B, buttons inputs as Button Normal or whatever you need

**Comment by jieweiyang** [comment]
It work as 5 buttons + 1 encoder, nothing special.

**Comment by 0xcore** [comment]
I'm going to try it.

Thanks!

**Comment by 0xcore** [comment]
Hi,

I don't know what happens but when I press the 4 directions stick in any of the four directions (A, B, C, D) the central push button (5) is also pressed. Pressing only the central push button (5) works as expected.

I have made the following connections:

![](https://i.gyazo.com/7c7103b6235c3bf42632cb18286a076d.png)

I have made the following connections:

A, B, C, D -> Button_VCC - POV Up, Down, Right, Left
5 -> Button_VCC - Normal Button
7,8 -> Button_VCC - Encoder A, Encoder B
6,9 -> +5V
10 -> GND

![](https://i.gyazo.com/26c622b57406f40eebeb3564b64796cd.png)

**Comment by vostrenkov** [comment]
This is exactly what logic table from datasheet says:
![image](https://user-images.githubusercontent.com/21309063/87761418-1974a080-c81a-11ea-8f3b-4f2427ec19cb.png)

Sorry i didnt mentioned this earlier. I will add POV_Center option for buttons settings for handling this state

**Comment by vostrenkov** [comment]
Please check v1.6.2. POV_Center added to buttons options for support this hardware

**Comment by 0x-Fede** [comment]
Work like a charm. Good Job!

**Comment by memob777** [comment]
Is possible for somebody to share the legs of the RKJXT1F42001 and how to connect them plz
I cant find the data on the data sheet
![RKJXT1F42001](https://user-images.githubusercontent.com/70198473/91637598-4b307800-ea12-11ea-833c-624c47b6a108.jpeg)

**Comment by AndyPeacock** [comment]
Hi, I'm about to try and use the same switch and its great to hear that it should work. I have some quick questions about connections though, hopefully someone can help. I'm planning to use a 4021 shift register to connect this up as I have done for all other connections. So far if I understand it correctly I have been connecting my switches between input to the shift register and ground (using [these ](https://oshpark.com/shared_projects/ta3Mpmcz) boards). So am I right in thinking that A,B,C,D, EncoderA, EncoderB and Com would all be connected to their own pin on the 4021, and Push and Encoder Com would go to one of the ground connections on the 2x8 connector? 

Sorry if this isn't the right place to post this.

Thanks

**Comment by vostrenkov** [comment]
Right, both Com pins should be connected to system ground and signal pins to shift register's input

**Comment by geologic** [comment]
Sorry to hijack this post, but how about connecting 2 of these switch? At "Button Config" tab i can see Pov1_ to Pov4_, but only one Encoder_A and Encoder_B

**Comment by AndyPeacock** [comment]
I think the encoders work differently. If you just set one of your encoder hardware pins to EncoderA and the other to EncoderB for each of your switches I think that will work. I don't have my switches hooked up yet, but this is how it works for standard rotary encoders for me. So you'll endup with mapping like:
 
1 Pov1_U
2 Pov1_D
3 Pov1_L
4 Pov1_R
5 Pov1_C
6 EncoderA 
7 EncoderB
8 Pov2_U
9 Pov2_D
10 Pov2_L
11 Pov2_R
12 Pov2_C
13 EncoderA 
14 EncoderB

Once you have that setup the encoders tab seems to recognise the pairs and show them correctly.

**Comment by geologic** [comment]
Thanks @AndyPeacock, i'll try that
