### ISSUE TITLE
Multiple Encoder Connection

### ISSUE THREAD

**Issue by 0xcore** [FreeJoy-Team/FreeJoy#37]
I am connecting several encoder in chain with 1N4148 diodes but I can't get it to work. The encoders do nothing when I connect the diodes according to the attached scheme, without diodes it works but causing multiple unwanted pulses between the two encoders.

PEC11R Encoders:
http://www.farnell.com/datasheets/2360546.pdf?_ga=2.13033214.817435842.1595327489-134403827.1586878496

Freejoy Config:
B12,B13 as Column Button
B14,B15 Column Row

Can FreeJoy work with this setup?

![imagen](https://user-images.githubusercontent.com/38330148/88050034-6a580200-cb56-11ea-88f4-f6790c34902a.png)

![imagen](https://user-images.githubusercontent.com/38330148/88049867-21a04900-cb56-11ea-9423-970877c42aa3.png)

![imagen](https://user-images.githubusercontent.com/38330148/88050615-755f6200-cb57-11ea-86e8-584301cfeb3b.png)

**Comment by vostrenkov** [comment]
It should work, but there may be a mistake in manual, so swap row and column assignments. I gonna check it also a bit later

**Comment by 0xcore** [comment]
Enconders work when swapping row and column but causing multiple unwanted pulses between the two encoders.

**Comment by vostrenkov** [comment]
I found a bug with encoder non-atomic access to buttons reading, wait for fix soon. Connection diagram in manual is also fixed

**Comment by 0xcore** [comment]
Thanks Yuri, I see another problem regarding encoders, maybe it's related.

![tempsnip3-ok](https://user-images.githubusercontent.com/38330148/88280017-57c00300-cce5-11ea-9eea-19327bb024f4.png)

![tempsnip4-ok](https://user-images.githubusercontent.com/38330148/88280022-5c84b700-cce5-11ea-84b2-5202ae0b864e.png)

**Comment by vostrenkov** [comment]
Thanks for the report. It is only visual issue and should not impact functionality. It will be fixed also

**Comment by vostrenkov** [comment]
Please check v1.6.2. It should fix the issue

**Comment by 0xcore** [comment]
Fixed, thanks!

Tested with 2 encoders.
B3,B4 as row. Encoder A & B pins
B5,B6 as column. Encoder Com

![imagen](https://user-images.githubusercontent.com/38330148/89404949-12ef8f80-d71b-11ea-9f59-19184eb93756.png)

![temp_encoder1](https://user-images.githubusercontent.com/38330148/89403166-336a1a80-d718-11ea-809e-7a1cbc0bcebd.PNG)
![temp_encoder2](https://user-images.githubusercontent.com/38330148/89403176-36fda180-d718-11ea-8627-e4e6cfb80bb0.PNG)
![temp_encoder3](https://user-images.githubusercontent.com/38330148/89403184-395ffb80-d718-11ea-9ac1-f2a19a70769f.PNG)
