### ISSUE TITLE
Analog Axes to Buttons

### ISSUE THREAD

**Issue by 0x-Fede** [FreeJoy-Team/FreeJoy#38]
Hi,

I can't get axes to buttons conversion to work. I'm trying with a 12 position rotary switch with a voltage divider but only 8 positions work. Analog raw read at positions 1 to 4 remains at 32.767, 5 to 12 between 28.0xx to -24.0xx

Is this setting correct in Freejoy Configurator?

Thanks!

1-4 Positions
![](https://i.gyazo.com/f0a603cf388758240bbbc7b7ac0db939.png)

5 Position
![imagen](https://user-images.githubusercontent.com/2559586/89204868-18cc6000-d5b7-11ea-8827-fe7e5a25fdee.png)

12 Position
![imagen](https://user-images.githubusercontent.com/2559586/89204596-a52a5300-d5b6-11ea-8278-8e64c152e146.png)

Axes to buttons
![imagen](https://user-images.githubusercontent.com/2559586/89204611-ac516100-d5b6-11ea-8e8a-2ce66ea555c2.png)

**Comment by vostrenkov** [comment]
Hello, 
do you connect your divider to 5V or to 3.3V?
If you show your connections it would be easier to analyze the issue

**Comment by 0x-Fede** [comment]
I have connected it to 5V, GND, A0, 1K resistors between pins. I don't know how to test in STM32 :( I have made a test in Arduino, analog reading seems correct, different output for each 12 positions of the rotary switch, values 90 to 1023.

Something similar to this with 12 pins.
![imagen](https://user-images.githubusercontent.com/2559586/89225916-5511b780-d5db-11ea-8024-b388abfb3b4e.png)

**Comment by vostrenkov** [comment]
STM32 have 3.3V supply voltage, so maximum input voltage should not exceed 3.3V. 
Connect your divider to 3.3V and it will show you something similar to what you got with arduino

**Comment by 0x-Fede** [comment]
Connected to 3.3V, now Axes Config works as expected. Thanks Yuri!
