### ISSUE TITLE
Encoder Type

### ISSUE THREAD

**Issue by 0x-Fede** [FreeJoy-Team/FreeJoy#44]
Encoders work 6x but I can't select encoder type.

![imagen](https://user-images.githubusercontent.com/2559586/91557176-4dbca000-e934-11ea-9c2d-1f22b80cfc7c.png)

**Comment by vostrenkov** [comment]
Please specify your encoder part number and show your buttons config for encoders

**Comment by 0x-Fede** [comment]
My fault. I was with Freejoy Configurator v1.6.0b5, I can select the encoder type with v1.6.2.b0 but I can't get it to work correctly.

The strange thing is that with 1.6.0b5 the encoder rotation were recognized by the FreeJoy Configurator & VKB but with the current version I can't get them to work, I have multiple unwanted pulses.

I don't know if it will be related but when connecting an stm32 configured with the Freejoy Configurator v1.6.0b5 in the Configurator v1.6.2b0 encoders function appear as POV Left & Down instead of Encoder A and Encoder B in Button Config. I have changed them to Encoder A and Encoder B but they don't work for me.

4x Rotary Encoder Matrix (A and B pins Button Row, Center pin Button Column) E1 config in Freejoy wiki

![imagen](https://user-images.githubusercontent.com/2559586/91635447-e87eb280-e9f8-11ea-8fdc-4e41f33a7ad2.png)

**Comment by vostrenkov** [comment]
Configurator version must match firmware version (except of number after "b" symbol). Otherwise board does not accept written config and other issues possible
