### ISSUE TITLE
Black pill?

### ISSUE THREAD

**Issue by rewsenj** [FreeJoy-Team/FreeJoy#47]
Hi I wanted to know if you plan on making this compatible with the STM32 black pill?

**Comment by vostrenkov** [comment]
Hi, it is compatible with any board with STM32F103. 
I know there are some bluepills boards with STM32F4 chips, they are planned to be supported later for FFB version of the software

**Comment by bayerla** [comment]
Working [https://github.com/FreeJoy-Team/FreeJoyConfigurator/issues/17](url)

**Comment by bayerla** [comment]
working [https://github.com/FreeJoy-Team/FreeJoyConfigurator/issues/17#issue-655216396](url)

**Comment by bayerla** [comment]
Working well !!
![grafik](https://user-images.githubusercontent.com/32127229/92331564-e3b0a300-f077-11ea-8dc0-670692b85572.png)

**Comment by rewsenj** [comment]
Ah yep, turns out I was being exceedingly dumb and neglected to click 'write config to device'... Thanks for the quick reply.

I have some other questions:

1: I've connected two different button matrices to the board but the software is reading them as one single matrix, is there any way to make it see them as separate matrices?

2: I've been struggling to connect a single button(as in one solitary button as opposed to a matrix)  to the board using either vcc/btn gnd or btn gnd/btn vcc. whenever I press the button the indicator doesn't change to green. It's not a fault with the button, I checked.

3: I've been trying to connect a hall sensor but it doesn't seem to be working, when I wave a magnet around it nothing happens. The sensors are [A1324LUA-T](https://www.digikey.com/product-detail/en/allegro-microsystems/A1324LUA-T/620-1432-ND/2728144). I tried with and without a 47µF capacitor (maybe too large capacitance?) but got nothing. I tried with a pot and it worked fine. Looking back at the website it says it needs a 4.5~5.5V supply so I probably just answered my own question. do you think [this](http://stm32duinoforum.com/forum/viewtopic_f_3_t_4176.html) is a viable solution?

Sorry I'm pretty new to this.

**Comment by vostrenkov** [comment]
1) No, only one matrix supported
2) Show your pins config or upload your config file. Do you have dynamic HID enabled?
3) Yes voltage is a possible reason. Try with 5 volts but you should use a voltage divider on signal to not exceed 3.3V on analog pin

**Comment by rewsenj** [comment]
Dynamic HID wasn't enabled, so I enabled it, but it still doesn't work.

![Screenshot (2)](https://user-images.githubusercontent.com/70842780/92384178-7ea48e00-f107-11ea-98b2-99f7ea91030d.png)

**Comment by vostrenkov** [comment]
I have it working with this config on v1.6.2b2.
Make sure you connect buttons right - in case of Button_VCC it should short pin to 3.3V or in case of Button_GND to GND

**Comment by rewsenj** [comment]
ah yep, the button is working now thx

It says [here](https://forum.hobbycomponents.com/viewtopic.php?t=2422) that the serial pins are 5v tolerant so is it fine to connect them without a divider (a3 and a4)?

**Comment by vostrenkov** [comment]
The picture also shows that a0-a7 pins are not 5V tolerant.
Also if you will get  more than 3.3V on axis input it will be counted as maximum value. So you can connect sensor supply to 5V but you have to make sure its output will fit 0 - 3.3V range

**Comment by rewsenj** [comment]
I'll get some Bidirectional LLCs

**Comment by vostrenkov** [comment]
Logic levels converters won't fit if you need analog input because they have logic output. Easiest way is to use voltage divider with 2 resistors

**Comment by rewsenj** [comment]
I'll get resistors then. 
I only have 10uF capacitors, is that too high or might they work?

**Comment by vostrenkov** [comment]
10uF between supply and gnd should be fine

**Comment by rewsenj** [comment]
haha it works! right now i'm using 1k and 2k resistors but I can go higher (up to 100k and 200k). what would you recommend?

**Comment by vostrenkov** [comment]
I'd recommend to stay in 10K - 100K range

**Comment by rewsenj** [comment]
Ok, I've managed to get it working. Mostly. The axis are connecting to the computer just fine but it doesn't seem to register the button presses (while freejoy configurator does). Any idea why?

**Comment by vostrenkov** [comment]
Have you done logic buttons setting according to wiki?

**Comment by rewsenj** [comment]
I've rewired it so there is only one matrix but now it's doing this:
![Screenshot 2020-09-21 141252](https://user-images.githubusercontent.com/70842780/93770878-b259da80-fc14-11ea-9a3e-e68556b5047a.png)
![Screenshot 2020-09-21 141339](https://user-images.githubusercontent.com/70842780/93770881-b2f27100-fc14-11ea-836d-f4050fb82c3b.png)

When I look at it in game controller it doesnt read any button presses exept when I press button 1 (lefthat1) where it reads it as all buttons being pressed

**Comment by vostrenkov** [comment]
This is exactly what it should do with configuration on your pic.
On buttons tab you should map your physical buttons (left part of the screen) to your logical buttons (right part of the screen). Logical buttons is what your game read, physical buttons is what you have connected to the controller, so phy.btns work as source for log.btns
Now you set all your logical buttons mapped to physical button 1, so all them triggered when you press phy.btn1

**Comment by rewsenj** [comment]
Oh, it all makes sense now. Everything is working. Thank you so much for your help, I wouldn't have gotten this far without it.

**Comment by pierre-vo** [comment]
@rewsenj does your black pill have a STM32F4 or STM32F103?

**Comment by makermindlane** [comment]
@vostrenkov I'd love to help bring support for stm32f4. Would be tremendous help if i could get a headstart or information about project architecture. :)

**Comment by vostrenkov** [comment]
> @vostrenkov I'd love to help bring support for stm32f4. Would be tremendous help if i could get a headstart or information about project architecture. :)

Work on porting to F4 is in progress. I believe it will be ready quite soon

**Comment by Monkeyja** [comment]
I want to know you have plans for implement ffb function or not 😅

**Comment by AlexanderIlyanok** [comment]
> > [@vostrenkov](https://github.com/vostrenkov) I'd love to help bring support for stm32f4. Would be tremendous help if i could get a headstart or information about project architecture. :)
> 
> Work on porting to F4 is in progress. I believe it will be ready quite soon

Hello. Do you have any info when f411 support will be added?
