### ISSUE TITLE
FreeJoy is workin but DCS dosen't recognize a button press.

### ISSUE THREAD

**Issue by Sparkowl** [FreeJoy-Team/FreeJoy#49]
The FreeJoy Board is recognized by Win10, all Buttons (via shift registers) and axes do work in the configuration app and in the system settings. When I try to bind a button in DCS or in IL2 it dosen't recognize a button press. Although it is visible in both. After starting up DCS with open System setting dialog for gamecontroller it showes no pressed button in there either.
My board does have the 10KOhm as R10 Resistor soldered. 
Thanks for your outstanding work.

**Comment by vostrenkov** [comment]
Hi,
If your controller operates in system control panel the problem is not with the device.
I'm not really familiar with DCS but I have two devices on freejoy working in IL2.
Once I had problems with mapping inputs in this game but it was solved by clearing /input/devices.txt file in game folder

**Comment by Sparkowl** [comment]
Thank you for your quick reply. I will try clearing the devices.txt

**Comment by Sparkowl** [comment]
I had the Freejoy connected over an USB 3.0 Hub. The problem disappeared after connecting it directly to the PC. Are there any limitations in conjunction with Hubs?

**Comment by vostrenkov** [comment]
I'm not sure, a lot may depend on used hub. I'm glad you managed to find a reason

**Comment by Sparkowl** [comment]
Thank's for your support and keep up the good work.
