### ISSUE TITLE
help

### ISSUE THREAD

**Issue by majidcactus2020** [FreeJoy-Team/FreeJoy#50]
Dear Sir  
Can STM32F103ZET6 be used in this program?

**Comment by vostrenkov** [comment]
Hi,
I don't see a reason why not but I have not tried that.
I can try with my f103nucleo board but i need some time to get to it

**Comment by IIIIIoppIIIII** [comment]
Hi! 
Is it possible to enter more than six characters in the USB custom name field?

**Comment by vostrenkov** [comment]
> Hi!
> Is it possible to enter more than six characters in the USB custom name field?

Hi, yes it supports up to 20 characters, but it is a bit bugged now. There are some troubles in entering device name after reading config back

**Comment by vostrenkov** [comment]
fixed in configurator

**Comment by IIIIIoppIIIII** [comment]
Thank you!

**Comment by majidcactus2020** [comment]
Dear sir,
 I know little about programming & software.
  STM32F103ZET6 has 144 -pin packages .
A higher number of keys and buttons can be used. and  keys  ,buttons, I use
for all aircraft.

I hope to near you very soon

Your faith fully

 Majid Eslamian

**Comment by vostrenkov** [comment]
There is limit of 128 buttons and 8 axis per usb hid device in windows. You can easily achieve 128 buttons on F103C8T6 using matrix connection or shift registers periphery
