### ISSUE TITLE
Combined axes functions

### ISSUE THREAD

**Issue by 0x-Fede** [FreeJoy-Team/FreeJoy#56]
Is it possible to combine two axes that work cooperatively ? I want to combine 2 analog inputs in one axis like old OSH combined axis function. I am not able to make it work.

Thanks!

From OSH :

"As you can see, there is also «Combined axis» function. It means you can combine 2 analog inputs in one axis. The function is mainly intended for rims with 2 clutch paddles. There are 2 possible modes:

- cooperative work — in this mode results from both analog inputs are summarized. You can choose weight of each input by slider.
- each on his own — each analog input works independently but for one axis. For example you can short calibrate an one input (paddle) for fast gear changes and an other calibrate as normal axis — for starting.

![imagen](https://user-images.githubusercontent.com/2559586/94179285-97010080-fe9c-11ea-808d-5ff6b4ad6b4d.png)

**Comment by vostrenkov** [comment]
Freejoy has flexible combined axes settings. You can choose plus, minus or equal function for axis and select which axis it is related.
Also you can set enabling this functionality on button press if needed
