### ISSUE TITLE
(｡･∀･)ﾉﾞHi Does FreeJoy support a 1/4 coder like CTS 288?

### ISSUE THREAD

**Issue by Bliss233** [FreeJoy-Team/FreeJoy#57]
(｡･∀･)ﾉﾞHi
Does FreeJoy support a 1/4 coder like CTS 288?

**Comment by vostrenkov** [comment]
Hi,
Yes, 1/4 encoders support present

**Comment by Bliss233** [comment]
> 嗨，
> 是的，目前支持1/4编码器

\(^o^)/~ Great, do I need to set up the encoder to use CTS288?I want to install 14 buttons and 5 encoders. Can the encoders be connected in parallel?

**Comment by vostrenkov** [comment]
We have wiki manual how to set up the controller:
https://www.github.com/FreeJoy-Team/FreeJoyWiki/tree/master/eng%2FEncoders-connection.md

**Comment by Bliss233** [comment]
![E LQ9B(X2ES ~YQ{`O8~@E5](https://user-images.githubusercontent.com/71959281/94358089-065f3600-00d1-11eb-85c8-4dfb5ec24a26.png)
![BSW1Y_SNY@4%X7S@Y15RX Q](https://user-images.githubusercontent.com/71959281/94358159-9bfac580-00d1-11eb-841d-7c7a433a5e6f.png)

Thank you very much. Can I connect the line this way?

**Comment by vostrenkov** [comment]
I think yes, but you will need to add diodes in this matrix
Better try it on devboard first

**Comment by Bliss233** [comment]
Thank you for your suggestion. After the encoder is connected, set them as Button ROW and Button Colum, so you can use 1/4 of the encoder for 2 buttons.

**Comment by Bliss233** [comment]
Hello, I'm having some problems, the encoder turns to 00 10, 12, 02, 00 after rotating to the left, and 00 02, 12, 10, 00 after rotating to the right. I use CTS 288 encoder 1/4, may I ask where to set it?
![image](https://user-images.githubusercontent.com/71959281/95295323-7035c780-08a9-11eb-94c2-067bbd6e96e6.png)
![image](https://user-images.githubusercontent.com/71959281/95295354-817ed400-08a9-11eb-9e72-3801e49acef7.png)
![image](https://user-images.githubusercontent.com/71959281/95295388-8e9bc300-08a9-11eb-8775-5757be28f86f.png)

**Comment by Bliss233** [comment]
I need to rotate the encoder 4 times to press the 1 button

**Comment by snubbsyuk** [comment]
> I need to rotate the encoder 4 times to press the 1 button

Hey, you need to go into the "Encoder" tab and select "Encoder_4x"
I use CTS 288 encoders and they work correctly with the above setting.

**Comment by Bliss233** [comment]
> > 我需要旋转编码器4次以按1按钮
> 
> 嗨，您需要进入“编码器”选项卡并选择“ Encoder_4x”。
> 我使用的是CTS 288编码器，它们在上述设置下可以正常工作。

I set the option of 4X, but it still needs to rotate 4 times to light up the button. Can I have a look at your Settings?

**Comment by vostrenkov** [comment]
> > > 我需要旋转编码器4次以按1按钮
> > 
> > 
> > 嗨，您需要进入“编码器”选项卡并选择“ Encoder_4x”。
> > 我使用的是CTS 288编码器，它们在上述设置下可以正常工作。
> 
> I set the option of 4X, but it still needs to rotate 4 times to light up the button. Can I have a look at your Settings?

Please show your settings on encoders tab. Is it possible you set resolution for wrong encoder or haven't written settings to the controller?

**Comment by snubbsyuk** [comment]
> > > 我需要旋转编码器4次以按1按钮
> > 
> > 
> > 嗨，您需要进入“编码器”选项卡并选择“ Encoder_4x”。
> > 我使用的是CTS 288编码器，它们在上述设置下可以正常工作。
> 
> I set the option of 4X, but it still needs to rotate 4 times to light up the button. Can I have a look at your Settings?

I've found I have to write the config to the device, unplug & replug USB for this kind of functionality to take effect.
