### ISSUE TITLE
Antivirus

### ISSUE THREAD

**Issue by kumrik** [FreeJoy-Team/FreeJoy#58]
Hi, my antivirus (Norton) deleted all .exe files automatically after unpacking. It says "setup.exe contained threat WS.Reputation.1". Is this project safe?

**Comment by vostrenkov** [comment]
Hi, 
which version did you get? current 1.6.2 version does not have any setup files

**Comment by kumrik** [comment]
Hi, I download two .rar files. Freejoy-master and FreeJoyConfigurator-master. All deleted files are in folder FreeJoyConfigurator-master/FreeJoyConfigurator/publish. Name deleted files: HidLibrara.dll; InWit.WiewModel.Ulits.dll; FreeJoy Configurator.exe; setup.exe

**Comment by vostrenkov** [comment]
Please use software from releases as described in wiki: https://github.com/FreeJoy-Team/FreeJoyWiki/blob/master/eng/Required-software.md

**Comment by kumrik** [comment]
Ok, thank you for info
