### ISSUE TITLE
Linux guide

### ISSUE THREAD

**Issue by 0xF1o** [FreeJoy-Team/FreeJoy#6]
I would like to contribute a guide for linux users (if thats ok for you).  
You can preview it here: https://github.com/piccaso/FreeJoy/wiki/Linux-guide  
But since this is part of the wiki I can't send you a web based pull request (or at least I don't know how).
So I think the only thing I can do here ist to request that you pull from `https://github.com/piccaso/FreeJoy.wiki.git` :)

**Comment by vostrenkov** [comment]
Oh, nice work!
I've added this page to wiki.
Thanks!

**Comment by 0xF1o** [comment]
you're welcome!
