### ISSUE TITLE
modifiers for encoders

### ISSUE THREAD

**Issue by NoSie** [FreeJoy-Team/FreeJoy#60]
Great stuff, thanks!

Question: are the modifiers (shift1-5) working with encoders? Would like to use one physical encoder to control several simulated com/nav instruments, depending on a sequential toggle. But the logical encoder buttons don't seem to care about the state of the modifier...

**Comment by vostrenkov** [comment]
Hi,
This has been reported in #46. I have already fixed this and pushed to master but not released yet.
Awaiting 1.6.2b4 very soon with this and some other fixes

**Comment by NoSie** [comment]
Perfect! Thanks a lot!
