### ISSUE TITLE
 there's a stagnation zone at -9 ??

### ISSUE THREAD

**Issue by tinglengyue** [FreeJoy-Team/FreeJoy#69]
I used two kinds of op but They are the same in that respect, I think So Hardware problems almost can be ruled out . When the pressure bar goes to -9, the pressure increases a little bit and there's a stagnation zone at -9  Close to 1/2 of the voltage   but why ??

**Comment by vostrenkov** [comment]
Please pin your configuration file

**Comment by tinglengyue** [comment]
After i download bootloader  and app.i do nothing  . Just default config file

**Comment by tinglengyue** [comment]
stm32F103C8T6    ADC at 0x400  0xc00  There's a nonlinear point here   ？？STM32 ADC bug？？？？The test uses stm32 small blue plate and a standard voltage source   At the same time use voltage source input voltage to A0 A1 A2  to test.

**Comment by tinglengyue** [comment]
![2020-1119-00：55](https://user-images.githubusercontent.com/32860608/99561773-4b815380-2a02-11eb-8812-64148638d34e.jpg)
![2020-1119-00：65](https://user-images.githubusercontent.com/32860608/99561805-5340f800-2a02-11eb-9d19-25940e33a8b6.jpg)

**Comment by vostrenkov** [comment]
I cannot reproduce your issue. Can you confirm that it is repeated on different boards?

**Comment by vostrenkov** [comment]
![stagnation test](https://user-images.githubusercontent.com/21309063/99564106-157ca900-29db-11eb-904a-9af2ea686954.gif)

**Comment by tinglengyue** [comment]
Yes, I can confirm that it is repeated on different boards。but  try debug with jtag 
i find adc values near 0x400  and 0xc00  did not move  when pressure increase a little bit.So, what I want to ask is there a bug in stm32f103 ADC?  Have you ever met this problem?

**Comment by tinglengyue** [comment]
It's like you haven't met。This is a little awkward

**Comment by tinglengyue** [comment]
This is a strange thing   Would you like to share  you sch?

**Comment by vostrenkov** [comment]
I have ordinary bluepill board without any external components. I also test it on my freejoy [controller board](https://github.com/FreeJoy-Team/Controller-Lite) with same result (watching values with SWD debug monitoring).
I've never faced such problem, any chance you use fake bluepills with fake STM32 MCU?
Do you check ADC behaviour with freejoy code only or you also try with clean ADC project?
