### ISSUE TITLE
Missing Shift Register functionality

### ISSUE THREAD

**Issue by godor2008** [FreeJoy-Team/FreeJoy#7]
On main page there is screenshot that has "Shift registers" tab. But when I launched config utility - there is no such tab :( Are there any plans/intentions to add such functionality?

**Comment by betgear** [comment]
This missing TAB is in the dev branch of the configurater code. I assume once the developer is happy with the changes and he has tested the changes to his satisfaction , the branches will be merged.

**Comment by vostrenkov** [comment]
Yes, shift registers functionality is nearly ready to be merged and released

**Comment by vostrenkov** [comment]
Now you can try shift registers functionality. Please check out [release page](https://github.com/vostrenkov/FreeJoy/releases) and [manuals](https://github.com/vostrenkov/FreeJoyConfigurator/wiki/Shift-registers).

**Comment by godor2008** [comment]
Cool man!

**Comment by godor2008** [comment]
Not issue, rather suggestion. I think it would be nice to be able to select GND or VCC at Shift register inputs.

**Comment by vostrenkov** [comment]
It is only reasonable for CD4021. 74HC165 has both inverted and non-inverted output.
Maybe i will add this later, now you can invert buttons on buttons tab

**Comment by godor2008** [comment]
Ah, got it, will try when my boards arrive

**Comment by vostrenkov** [comment]
Now shift registers have pull-up and pull-down selection
