### ISSUE TITLE
74HC165 Shift Register 

### ISSUE THREAD

**Issue by 0x-Fede** [FreeJoy-Team/FreeJoy#72]
Hi,

Is this connection correct for a shift register to work?

A5 -> Latch
A4 -> Data
B3 -> SCK

74HC165 push buttons pins are disconnected. 
74HC165 Pull Down.

Thanks!

![imagen](https://user-images.githubusercontent.com/2559586/100771037-380cba00-33fe-11eb-98eb-0b5a39e9af5d.png)
![imagen](https://user-images.githubusercontent.com/2559586/100771538-d0a33a00-33fe-11eb-8feb-984a074687bc.png)
![imagen](https://user-images.githubusercontent.com/2559586/100771598-e1ec4680-33fe-11eb-8ad1-90e011f8a270.png)

![63a78fb7b1fbb197b9044292cbe7d669](https://user-images.githubusercontent.com/2559586/100772224-a3a35700-33ff-11eb-8d70-84741266ff39.gif)

**Comment by vostrenkov** [comment]
Hi!
Connections looks right but you need to add pull-up or pull-down resistors on shift register inputs to prevent this flickering

**Comment by 0x-Fede** [comment]
Ok Yuri, thanks!
