### ISSUE TITLE
Shift Modifiers on Encoders 

### ISSUE THREAD

**Issue by AndyPeacock** [FreeJoy-Team/FreeJoy#73]
I have one encoder set up with logical outputs for unmodified (3,4), shift1 (5,6) and shift 2 (7,8) states. Shift1 (1) and shift2 (2) are controlled by a toggle switch and work correctly. When no modifier is active, logical 3 and 4 come on as I rotate the encoder. If I enable shift1, logical 5 and 6 come on as I rotate, as expected, but I also see 3 and 4 (unmodified state) come on too, the same applied for shift2. 

I understand that the unmodified logical output should not come on, if there is also a shifted output setup, but the shift is not active. _If physical button has both logical buttons with shift modificator and without them, then the logical button which has no modificator will work only if shift modificators are not pressed._ I'm on the device firmware 1.6.2b4.

![screen](https://user-images.githubusercontent.com/41367524/100807836-eaf30d00-342a-11eb-9983-29b9a5bdeb6c.jpg)

**Comment by vostrenkov** [comment]
Hi,
there's known issue on shifts with encoders. It will be fixed soon

**Comment by vostrenkov** [comment]
should be fixed now
