### ISSUE TITLE
7 way encoder

### ISSUE THREAD

**Issue by vorph666** [FreeJoy-Team/FreeJoy#75]
Hi,
I´m building a steering wheel button box. I want to use two 7 way encoders. 
Up, down, left, right, rotate left, rotate right, press button. 

When now switching to any direction, the press button is also activated. Do you have any idea, how to fix this behavior?
It is ok when rotating left or right.

Thanks

![Screenshot 2020-12-05 135258](https://user-images.githubusercontent.com/75529747/101243620-c5ebec00-3701-11eb-98b5-9ef4df55e767.png)

**Comment by snubbsyuk** [comment]
Hey,
You need to use the POV_center "function" for the push button - this will eliminate the issue you're facing.

Cheers

**Comment by vorph666** [comment]
Great, that was easy. It works. Thanks!
