### ISSUE TITLE
Device usb name

### ISSUE THREAD

**Issue by p33t-r** [FreeJoy-Team/FreeJoy#76]
Hi, is it normal/intended that the custom USB device name set in FreeJoy Configurator does show up correctly in Windows Devices, but in any game or in Windows HID Control Panel it always shows the default "FreeJoy"?

**Comment by vostrenkov** [comment]
https://github.com/FreeJoy-Team/FreeJoyConfigurator/issues/27

**Comment by p33t-r** [comment]
Thank you and sorry I couldn't find this issue mentioned before. Greatly appreciate your work on Freejoy!
