### ISSUE TITLE
Shift Register CLK to any PIN, not only SPI_SCK B3

### ISSUE THREAD

**Issue by godor2008** [FreeJoy-Team/FreeJoy#8]
Greetings! Is it possible to make programmable CLK assignable for any pin for SHIFT registers? Same way as it is done for ShiftReg_DATA or ShiftReg_LATCH. In latest release I see that it is only possible to use pin B3

**Comment by vostrenkov** [comment]
It is possible, but i want to have all serial devices (TLE sensors and shift registers) connected to common SPI  clock line to reduce amount of the used pins

**Comment by godor2008** [comment]
So you are using hardware clock source

**Comment by vostrenkov** [comment]
It is hardware for TLE and software for shift registers. Pin configuration changes during runtime
