### ISSUE TITLE
Axis buttons triggers

### ISSUE THREAD

**Issue by wizhippo** [FreeJoy-Team/FreeJoy#81]
Do the axis buttons triggers based on the logical axis or the raw value?  If not it would be nice to be able to select which.

I wish to trigger on the raw value as my axis curve has a flat beginning and I wish to trigger the button at a point in this area.

**Comment by vostrenkov** [comment]
Hi,
axis buttons affected by logical axis.
If you dont have all 8 axis mapped you can add another "hidden" logical axis with same raw source and use it for axis buttons.
