### ISSUE TITLE
MCP3204 issue

### ISSUE THREAD

**Issue by ivannunyadambiz** [FreeJoy-Team/FreeJoy#83]
so i have an MCP3204 connected but the measured values are total garbage, jumping around and in no relation to the analog input signal. the schematic is attached. any help greatly appreciated.
[ControllerBoard.pdf](https://github.com/FreeJoy-Team/FreeJoy/files/5775960/ControllerBoard.pdf)

**Comment by vostrenkov** [comment]
I confirm there is a bug with MCP32xx line. Working on fix

**Comment by ivannunyadambiz** [comment]
Fixed?

**Comment by vostrenkov** [comment]
Yes, it should be ok in 1.7.0
