### ISSUE TITLE
G27 encoder

### ISSUE THREAD

**Issue by LosTigeros** [FreeJoy-Team/FreeJoy#90]
Hello.

Is it possible to use bultin rotary/optical encoder in G27?
Processor in the motherboard of my G27 died so I'm looking for alternatives.

**Comment by vostrenkov** [comment]
Hi,
yes, it is possible to use it as "fast encoder" on A8 and A9 pins

**Comment by LosTigeros** [comment]
Okay, thanks for that great project!

**Comment by LosTigeros** [comment]
How can I set it up as X axis? After connecting it to pins A8 as A and A9 as B and setting Axis source as Encoder it just switches between -1 and 0 when the wheel is rotating.
![AHU6tu64oj](https://user-images.githubusercontent.com/6253928/105989585-a0e07d80-60a1-11eb-8283-c19a8e2756a1.gif)

**Comment by vostrenkov** [comment]
Did you set A8 and A9 to Fast_Encoder on Pins tab?

**Comment by vostrenkov** [comment]
Also your wiring should include pull-up resistors for the encoders inputs
https://www.github.com/FreeJoy-Team/FreeJoyWiki/tree/master/images%2FA1.7.jpg

**Comment by LosTigeros** [comment]
Pins:
![image](https://user-images.githubusercontent.com/6253928/105994881-81991e80-60a8-11eb-8042-9b5a1c0dcfdb.png)

Encoder:
![image](https://user-images.githubusercontent.com/6253928/105995034-b4431700-60a8-11eb-9b16-8105d6f85710.png)

Connection:
![MVIMG_20210127_191502](https://user-images.githubusercontent.com/6253928/106035414-65ab7200-60d4-11eb-906d-9e9b185e097c.jpg)
![MVIMG_20210127_185630](https://user-images.githubusercontent.com/6253928/106035421-680dcc00-60d4-11eb-86d6-4099e2d2fc18.jpg)
![MVIMG_20210127_185556](https://user-images.githubusercontent.com/6253928/106035422-693ef900-60d4-11eb-9822-969852ae3c31.jpg)


Now it changes between 0 and 1

**Comment by LosTigeros** [comment]
When rotating the encoder I get:
`80mV` or `4.37V` on `A8`
`80mV` or `1.137V` on `A9`

Edit: After adding level shifter it works fine!
